[package]
name = "opa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
httpmock = "0.6.*"
atty = "0.2"

[dependencies]
tokio = {version = "1.18.*", features = ["rt-multi-thread"]}
rocket = {version = "0.5.0-rc", features = ["json"]}
serde = {version = "1", features = ["derive"]}
reqwest = {version = "0.11.*", features = ["json"]}
thiserror = "1.0.*"
anyhow = "1.0.*"
once_cell = "1.10.*"
log = "0.4.*"
fern = "0.6.*"
regex = "1.5.*"
parking_lot = "0.12.*"
chrono = {version = "0.4.*", features = ["serde"]}
uuid = {version = "0.8.*", features = ["v4"]}
notify = "5.0.0-pre.13"
figment = {version = "0.10.*", features = ["yaml"]}
opentelemetry = "0.17.*"
prometheus = "0.13.*"
opentelemetry-prometheus = "0.10.*"
hmac = "0.12.*"
sha2 = "0.10.*"
harsh = "0.2.*"
hex = "0.4.*"
rs-utils = {git = "https://gitlab.w6d.io/w6d/rust/rs-utils"}
clap = "2.33"
proptest = "0.9"
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
atty = "0.2"
opa-wasm = {git = "https://gitlab.w6d.io/w6d/rust/rs-opa"}
opa-go = {git = "https://gitlab.w6d.io/w6d/rust/rs-opa"}
walkdir = "2"
curl = "0.4.43"
heapless = "0.7.10"
base64 = "0.13.0"

[dependencies.rslib]
git = "https://gitlab.w6d.io/w6d/library/rslib"
default-features = false
features = ["kafka"]
