kafka:
  service: "127.0.0.1:58640"
  topics:
    error: 'opa-error'

salt: jlHQJMtz70WrDrsmrPEcnFeoCYEa3oIi
salt_length: 16

http:
  kratos: 'http://kratos.kratos:4434/admin/identities/'
grpc:
  project: 'http://project:8081/'

env:
  - name: RUST_LOG
    value: 'debug'
  - name: TASK_LIMIT
    value: '50'

redis:
  enabled: false


