kafka:
  service: '127.0.0.1:58640'
  topics:
    error: 'opa-error'
salt: "examples"
salt_length: 40
http:
  kratos: 'http://localhost:4434/admin/identities/'
  project: 'http://project:8080/health/ready'
grpc:
  project: 'http://project:8080/'